/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Login.java
 *
 * Created on 4 Aug, 2011, 8:47:35 PM
 */
package com.employeeManagementSystem.ui;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;

import com.employeeManagementSystem.dao.LoginDaoImpl;
import com.employeeManagementSystem.domain.Employee;

/**
 *
 * @author sourabh
 */
public class LoginPage extends javax.swing.JPanel {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/** Creates new form Login */
    
    private MainPage mainPage;
    // Variables declaration - do not modify
    private JButton jButtonLogin;
    private JButton jButtonSignUp;
    private JLabel jLabelLoginId;
    private JLabel jLabelPassword;
    private JTextField jTextFieldLoginId;
    private JTextField jTextFieldPassword;
    // End of variables declaration
    
    public LoginPage(MainPage mainPage) {
        initComponents();
        this.mainPage=mainPage;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    
    private void initComponents() {

        jLabelLoginId = new javax.swing.JLabel();
        jTextFieldLoginId = new javax.swing.JTextField();
        jLabelPassword = new javax.swing.JLabel();
        jTextFieldPassword = new javax.swing.JTextField();
        jButtonLogin = new javax.swing.JButton();
        jButtonSignUp = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(500, 500));

        jLabelLoginId.setText("User Name:");

        jLabelPassword.setText("Password :");

        jButtonLogin.setText("Login");
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });

        jButtonSignUp.setText("SignUp");
        jButtonSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSignUpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelPassword)
                            .addComponent(jLabelLoginId))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldPassword)
                            .addComponent(jTextFieldLoginId, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jButtonLogin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonSignUp)))
                .addContainerGap(249, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLoginId)
                    .addComponent(jTextFieldLoginId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPassword)
                    .addComponent(jTextFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLogin)
                    .addComponent(jButtonSignUp))
                .addContainerGap(387, Short.MAX_VALUE))
        );
    }// </editor-fold>

    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) { 
    	Employee employee = new Employee();
    	employee.setUserName(jLabelLoginId.getText());
    	employee.setPassword(jTextFieldPassword.getText());
    	LoginDaoImpl loginDao = new LoginDaoImpl();
    	loginDao.login(employee);
        this.mainPage.getCardLayout().show(mainPage.getCardPanel(), MainPage.LOGIN_SUCESSFUL);
        
    }                                            

    private void jButtonSignUpActionPerformed(java.awt.event.ActionEvent evt) {                                             
        this.mainPage.getCardLayout().show(mainPage.getCardPanel(), MainPage.REGISTRATION);
    }                                             

    
}
