/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RegistrationSucessful.java
 *
 * Created on 7 Aug, 2011, 12:35:46 AM
 */
package com.employeeManagementSystem.ui;

import javax.swing.JButton;
import javax.swing.JLabel;


/**
 *
 * @author sourabh
 */
public class RegistrationSucessfulPage extends javax.swing.JPanel {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/** Creates new form RegistrationSucessful */
    MainPage mainPage;
    public RegistrationSucessfulPage(MainPage mainPage) {
        this.mainPage = mainPage;
        System.out.println("second"+this.mainPage.getEmployee());
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    
    private void initComponents() {
//    	LoginDaoImpl loginDaoImpl = new LoginDaoImpl();
//    	loginDaoImpl.createEmployee(new Employee());
        jLabelRegistraionSucessful = new JLabel();
        jLabelFirstName = new JLabel();
        jLabelMiddleName = new JLabel();
        jLabelLastName = new JLabel();
        jLabelUserName = new JLabel();
        jLabelPassword = new JLabel();
        jLabelSecurityQuestion = new JLabel();
        jLabelSecurityAnswer = new JLabel();
        jLabelDatabaseFirstName = new JLabel();
        jLabelDatabaseMiddleName = new JLabel();
        jLabelDatabaseLastName = new JLabel();
        jLabelDatabaseUserName = new JLabel();
        jLabelDatabasePassword = new JLabel();
        jLabelDatabaseSecurityQuestion = new JLabel();
        jLabelDatabaseSecurityAnswer = new JLabel();
        jButton1 = new javax.swing.JButton();

        jLabelRegistraionSucessful.setText("Registraion Sucessful................");

        jLabelFirstName.setText("First Name :");

        jLabelMiddleName.setText("Middle Name :");

        jLabelLastName.setText("Last Name :");

        jLabelUserName.setText("UserName :");

        jLabelPassword.setText("Password :");

        jLabelSecurityQuestion.setText("Security Question :");

        jLabelSecurityAnswer.setText("Security Answer :");

        jButton1.setText("Go To Login");
        
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelRegistraionSucessful)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelFirstName)
                            .addComponent(jLabelMiddleName)
                            .addComponent(jLabelLastName)
                            .addComponent(jLabelUserName)
                            .addComponent(jLabelPassword))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelDatabaseFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                            .addComponent(jLabelDatabaseMiddleName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelDatabaseLastName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelDatabaseUserName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelDatabasePassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelSecurityQuestion)
                            .addComponent(jLabelSecurityAnswer))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelDatabaseSecurityAnswer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelDatabaseSecurityQuestion, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                            .addComponent(jButton1))))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabelRegistraionSucessful)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFirstName)
                    .addComponent(jLabelDatabaseFirstName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMiddleName)
                    .addComponent(jLabelDatabaseMiddleName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLastName)
                    .addComponent(jLabelDatabaseLastName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelUserName)
                    .addComponent(jLabelDatabaseUserName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPassword)
                    .addComponent(jLabelDatabasePassword))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSecurityQuestion)
                    .addComponent(jLabelDatabaseSecurityQuestion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSecurityAnswer)
                    .addComponent(jLabelDatabaseSecurityAnswer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(84, Short.MAX_VALUE))
        );
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
    	mainPage.getCardLayout().show(mainPage.getCardPanel(), MainPage.TABLE_EXAMPLE);
    }
    
    // Variables declaration - do not modify
    private JButton jButton1;
    private JLabel jLabelDatabaseFirstName;
    private JLabel jLabelDatabaseLastName;
    private JLabel jLabelDatabaseMiddleName;
    private JLabel jLabelDatabasePassword;
    private JLabel jLabelDatabaseSecurityAnswer;
    private JLabel jLabelDatabaseSecurityQuestion;
    private JLabel jLabelDatabaseUserName;
    private JLabel jLabelFirstName;
    private JLabel jLabelLastName;
    private JLabel jLabelMiddleName;
    private JLabel jLabelPassword;
    private JLabel jLabelRegistraionSucessful;
    private JLabel jLabelSecurityAnswer;
    private JLabel jLabelSecurityQuestion;
    private JLabel jLabelUserName;
    // End of variables declaration
}
