package com.employeeManagementSystem.ui;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.SwingWorker;
import com.employeeManagementSystem.dao.LoginDaoImpl;
import com.employeeManagementSystem.domain.Employee;

/**
 * 
 * @author sourabh
 */
public class RegistrationPage extends javax.swing.JPanel {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/** Creates new form Register */
	MainPage mainPage;

	public RegistrationPage(MainPage mainPage) {
		this.mainPage = mainPage;
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */

	private void initComponents() {

		jLabelFirstName = new JLabel();
		jLabelMiddleName = new JLabel();
		jTextFieldMiddleName = new JTextField();
		jLabelLastName = new JLabel();
		jLabelSecurityQuestion = new JLabel();
		jTextFieldFirstName = new JTextField();
		jTextFieldLastName = new JTextField();
		jButtonRegister = new JButton();
		jTextFieldSecurityQuestion = new JTextField();
		jLabelSecurityAnswer = new JLabel();
		jTextFieldSecurityAnswer = new JTextField();
		jLabelPassword = new JLabel();
		jPasswordFieldPassword = new JPasswordField();

		jLabelFirstName.setText("First Name :");

		jLabelMiddleName.setText("Middle Name :");

		jLabelLastName.setText("Last Name :");

		jLabelSecurityQuestion.setText("Security Question :");

		jButtonRegister.setText("Register");
		jButtonRegister.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonRegisterActionPerformed(evt);
			}
		});

		jLabelSecurityAnswer.setText("Security Answer :");

		jLabelPassword.setText("Password :");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup().addGap(116, 116, 116)
						.addComponent(jButtonRegister)
						.addContainerGap(211, Short.MAX_VALUE))
						.addGroup(
								layout.createSequentialGroup()
								.addGap(39, 39, 39)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jLabelLastName)
												.addComponent(
														jLabelSecurityQuestion)
														.addComponent(jLabelMiddleName)
														.addComponent(jLabelFirstName)
														.addComponent(
																jLabelSecurityAnswer)
																.addComponent(jLabelPassword))
																.addGap(24, 24, 24)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addGroup(
																						layout.createSequentialGroup()
																						.addGroup(
																								layout.createParallelGroup(
																										javax.swing.GroupLayout.Alignment.LEADING)
																										.addComponent(
																												jTextFieldLastName,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												102,
																												Short.MAX_VALUE)
																												.addComponent(
																														jTextFieldFirstName,
																														javax.swing.GroupLayout.DEFAULT_SIZE,
																														102,
																														Short.MAX_VALUE)
																														.addComponent(
																																jTextFieldMiddleName,
																																javax.swing.GroupLayout.DEFAULT_SIZE,
																																102,
																																Short.MAX_VALUE))
																																.addContainerGap(
																																		143,
																																		javax.swing.GroupLayout.PREFERRED_SIZE))
																																		.addGroup(
																																				layout.createSequentialGroup()
																																				.addGroup(
																																						layout.createParallelGroup(
																																								javax.swing.GroupLayout.Alignment.TRAILING)
																																								.addComponent(
																																										jTextFieldSecurityAnswer,
																																										javax.swing.GroupLayout.Alignment.LEADING,
																																										javax.swing.GroupLayout.DEFAULT_SIZE,
																																										235,
																																										Short.MAX_VALUE)
																																										.addComponent(
																																												jTextFieldSecurityQuestion,
																																												javax.swing.GroupLayout.Alignment.LEADING,
																																												javax.swing.GroupLayout.DEFAULT_SIZE,
																																												235,
																																												Short.MAX_VALUE)
																																												.addComponent(
																																														jPasswordFieldPassword,
																																														javax.swing.GroupLayout.Alignment.LEADING,
																																														javax.swing.GroupLayout.DEFAULT_SIZE,
																																														235,
																																														Short.MAX_VALUE))
																																														.addContainerGap()))));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
						.addGap(20, 20, 20)
						.addGroup(
								layout.createParallelGroup(
										javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(
												jTextFieldFirstName,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabelFirstName))
												.addPreferredGap(
														javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addGroup(
																layout.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.BASELINE)
																		.addComponent(
																				jTextFieldMiddleName,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(jLabelMiddleName))
																				.addPreferredGap(
																						javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																						.addGroup(
																								layout.createParallelGroup(
																										javax.swing.GroupLayout.Alignment.BASELINE)
																										.addComponent(
																												jTextFieldLastName,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																												.addComponent(jLabelLastName))
																												.addPreferredGap(
																														javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																														.addGroup(
																																layout.createParallelGroup(
																																		javax.swing.GroupLayout.Alignment.BASELINE)
																																		.addComponent(
																																				jTextFieldSecurityQuestion,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				javax.swing.GroupLayout.DEFAULT_SIZE,
																																				javax.swing.GroupLayout.PREFERRED_SIZE)
																																				.addComponent(
																																						jLabelSecurityQuestion))
																																						.addPreferredGap(
																																								javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																								.addGroup(
																																										layout.createParallelGroup(
																																												javax.swing.GroupLayout.Alignment.BASELINE)
																																												.addComponent(
																																														jTextFieldSecurityAnswer,
																																														javax.swing.GroupLayout.PREFERRED_SIZE,
																																														javax.swing.GroupLayout.DEFAULT_SIZE,
																																														javax.swing.GroupLayout.PREFERRED_SIZE)
																																														.addComponent(
																																																jLabelSecurityAnswer))
																																																.addPreferredGap(
																																																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																																		.addGroup(
																																																				layout.createParallelGroup(
																																																						javax.swing.GroupLayout.Alignment.BASELINE)
																																																						.addComponent(jLabelPassword)
																																																						.addComponent(
																																																								jPasswordFieldPassword,
																																																								javax.swing.GroupLayout.PREFERRED_SIZE,
																																																								javax.swing.GroupLayout.DEFAULT_SIZE,
																																																								javax.swing.GroupLayout.PREFERRED_SIZE))
																																																								.addPreferredGap(
																																																										javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																																																										32, Short.MAX_VALUE)
																																																										.addComponent(jButtonRegister)
																																																										.addGap(75, 75, 75)));
	}

	@SuppressWarnings("deprecation")
	private void jButtonRegisterActionPerformed(java.awt.event.ActionEvent evt) {


		new SwingWorker<Void, Void>() {
			@Override
			protected Void doInBackground() throws Exception {
				Employee employee =new Employee();
				employee.setFirstName(jTextFieldFirstName.getText());
				employee.setMiddleName(jTextFieldMiddleName.getText());
				employee.setLastName(jTextFieldLastName.getText());
				employee.setSecurityQuestion(jTextFieldSecurityQuestion.getText());
				employee.setSecurityAnswer(jTextFieldSecurityAnswer.getText());
				employee.setPassword(jPasswordFieldPassword.getText());
				//this.mainPage.setEmployee(employee);
				System.out.println("first" + employee);
				LoginDaoImpl loginDao = new LoginDaoImpl();
				loginDao.createEmployee(employee);
				return null;
			}
		}.execute();

		mainPage.getCardLayout().show(mainPage.getCardPanel(),
				MainPage.REGISTRATION_SUCESSFUL);
	}

	// Variables declaration - do not modify
	private JButton jButtonRegister;
	private JLabel jLabelFirstName;
	private JLabel jLabelLastName;
	private JLabel jLabelMiddleName;
	private JLabel jLabelPassword;
	private JLabel jLabelSecurityAnswer;
	private JLabel jLabelSecurityQuestion;
	private JPasswordField jPasswordFieldPassword;
	private JTextField jTextFieldFirstName;
	private JTextField jTextFieldLastName;
	private JTextField jTextFieldMiddleName;
	private JTextField jTextFieldSecurityAnswer;
	private JTextField jTextFieldSecurityQuestion;
	// End of variables declaration
}
